defaults: &defaults
  docker:
    - image: quay.io/stevector/docker-build-tools-ci:latest
  working_directory: ~/example_drops_8_composer
  environment:
    TZ: "/usr/share/zoneinfo/America/Chicago"

    ADMIN_USERNAME: admin
    BUILD_TOOLS_VERSION: dev-master
    TERM: dumb

version: 2
jobs:    build:
        <<: *defaults
        steps:
            - checkout

            - run:
                name: Set variables
                command: ./scripts/circle-ci/variables.sh

            - run:
                name: everything
                command: |
                    ./scripts/circle-ci/install-globals.sh
                    composer install  --optimize-autoloader --ignore-platform-reqs
                    composer circle-tests
                    ./scripts/circle-ci/deploy-to-multidev.sh
                    ./scripts/circle-ci/add-behat-users.sh
                    ./scripts/circle-ci/run-migration.sh
                    ./scripts/circle-ci/migration-behat.sh
                    cd backstop && ./run-backstop.sh

    behavioral:
        <<: *defaults
        steps:
            - checkout

            - restore_cache:
                keys:
                    - composer-{{ checksum "composer.lock" }}

            - run:
                name: variables
                command: ./scripts/circle-ci/variables.sh

            - run:
                command: ./scripts/circle-ci/install-globals.sh

            - run:
                command: composer install  --optimize-autoloader --ignore-platform-reqs

            - save_cache:
                key: composer-{{ checksum "composer.lock" }}
                paths:
                  - vendor

            - run:
                name: everything
                command: |
                    composer install  --optimize-autoloader --ignore-platform-reqs
                    composer circle-tests
                    ./scripts/circle-ci/deploy-to-multidev.sh
                    ./scripts/circle-ci/add-behat-users.sh
                    ./scripts/circle-ci/clickdriving-behat.sh

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - behavioral
