defaults: &defaults
  docker:
    - image: quay.io/stevector/docker-build-tools-ci:latest
  working_directory: ~/example_drops_8_composer
  environment:
    TZ: "/usr/share/zoneinfo/America/Los_Angeles"
    ADMIN_USERNAME: admin
    BUILD_TOOLS_VERSION: dev-master
    TERM: dumb

version: 2
jobs:
    build:
        <<: *defaults
        steps:
            - checkout

            - restore_cache:
                keys:
                    - composer-{{ checksum "composer.lock" }}

            - run:
                name: variables
                command: ./scripts/circle-ci/variables.sh

#            - run:
#                command: ./scripts/circle-ci/install-globals.sh
#
#            - run:
#                command: composer install  --optimize-autoloader --ignore-platform-reqs
#
#            - save_cache:
#                key: composer-{{ checksum "composer.lock" }}
#                paths:
#                  - vendor
#
#            - run:
#                command: composer circle-tests
#
#            - run:
#                name: everything
#                command: |
#                    ./.circleci/deploy/deploy-to-multidev.sh
#                    ./.circleci/deploy/run-migration.sh
#
#            - run:
#                name: Behat
#                command: |
#                    ./.circleci/behat-runners/add-behat-users.sh
#                    ./.circleci/behat-runners/migration-behat.sh

            - run:
                name: Set TERMINUS_ENV for Backstop
                command: |
                    mkdir globals
                    echo $TERMINUS_ENV > globals/TERMINUS_ENV

            - persist_to_workspace:
                # Must be relative path from working_directory
                root: .
                # Must be relative path from root
                paths:
                    - globals



    backstop:
        <<: *defaults
        steps:
            - checkout












    backstop:
        docker:
            - image: quay.io/stevector/pantheon-ci-testing:latest
        working_directory: ~/example_drops_8_composer
        steps:
            - checkout



            - attach_workspace:
                # Must be absolute path or relative path from working_directory
                at: /tmp



            - run:
                name: Global vars
                # Set TERMINUS_ENV and related environment variables.
                # https://github.com/stevector/docker-build-tools-ci/blob/master/dockerfiles/pantheon-ci-testing/scripts/set-up-global-vars.sh
                command: /build-tools-ci/scripts/set-up-global-vars.sh


            - run:
                name: check var
                command: |
                cat /tmp/globals/TERMINUS_ENV
                TERMINUS_ENV=$(cat /tmp/globals/TERMINUS_ENV)
                echo 'export TERMINUS_ENV=${TERMINUS_ENV}' >> $BASH_ENV

            - run:
                name: check var
                command: |
                echo $TERMINUS_ENV


            - run:
                name: run-backstop
                command: cd backstop && ./run-backstop.sh
            - store_artifacts:
                path: /tmp/artifacts
                destination: artifacts






















    behavioral:
        <<: *defaults
        steps:
            - checkout

            - restore_cache:
                keys:
                    - composer-{{ checksum "composer.lock" }}

            - run:
                name: variables
                command: ./scripts/circle-ci/variables.sh

            - run:
                command: ./scripts/circle-ci/install-globals.sh

            - run:
                command: composer install  --optimize-autoloader --ignore-platform-reqs

            - save_cache:
                key: composer-{{ checksum "composer.lock" }}
                paths:
                  - vendor

            - run:
                command: composer circle-tests

            - run:
                command: ./.circleci/deploy/deploy-to-multidev.sh

            - run:
                name: Behat
                command: |
                    ./.circleci/behat-runners/add-behat-users.sh
                    ./.circleci/behat-runners/clickdriving-behat.sh


workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - backstop:
          requires:
             - build
 #     - behavioral
