# https://circleci.com/docs/2.0/workflows/#using-workspaces-to-share-data-among-jobs
defaults: &defaults
  docker:
    - image: quay.io/stevector/docker-build-tools-ci:latest
  working_directory: ~/example_drops_8_composer
  environment:
    #=========================================================================
    # In addition to the environment variables defined in this file, also
    # add the following variables in the Circle CI UI.
    #
    # See: https://circleci.com/docs/2.0/environment-variables/
    #
    # TERMINUS_SITE:  Name of the Pantheon site to run tests on, e.g. my_site
    # TERMINUS_TOKEN: The Pantheon machine token
    # GITHUB_TOKEN:   The GitHub personal access token
    # GIT_EMAIL:      The email address to use when making commits
    #
    # TEST_SITE_NAME: The name of the test site to provide when installing.
    # ADMIN_PASSWORD: The admin password to use when installing.
    # ADMIN_EMAIL:    The email address to give the admin when installing.
    #=========================================================================
    TZ: "/usr/share/zoneinfo/America/Los_Angeles"

    # The variables below usually do not need to be modified.

    #======================================================================================================================================
    # Circle CI 2.0 does not yet expand environment variables so they have to be manually EXPORTed
    # Once environment variables can be expanded the variables below can be uncommented and the EXPORTs in set-up-globals.sh can be removed
    # See: https://discuss.circleci.com/t/unclear-how-to-work-with-user-variables-circleci-provided-env-variables/12810/11
    # See: https://discuss.circleci.com/t/environment-variable-expansion-in-working-directory/11322
    # See: https://discuss.circleci.com/t/circle-2-0-global-environment-variables/8681
    #======================================================================================================================================

    NOTIFY: 'scripts/github/add-commit-comment {project} {sha} "Created multidev environment [{site}#{env}]({dashboard-url})." {site-url}'
    ADMIN_USERNAME: admin
    BUILD_TOOLS_VERSION: dev-master
    TERM: dumb

version: 2
jobs:
    # @todo: common initialization: 'composer install' for the site-under-test
    build:
        <<: *defaults
        steps:
            - checkout

            - run:
                # Set TERMINUS_ENV and related environment variables.
                # https://github.com/pantheon-systems/docker-build-tools-ci/blob/1.x/scripts/set-environment
                name: dependencies
                command: ./scripts/circle-ci/variables.sh

            - run:
                name: everything
                command: |
                    ./scripts/circle-ci/install-globals.sh
                    composer install  --optimize-autoloader --ignore-platform-reqs
                    composer circle-tests
                    ./scripts/circle-ci/deploy-to-multidev.sh
                    cd backstop && ./run-backstop.sh

    behavioral:
        <<: *defaults
        steps:
            - checkout

            - restore_cache:
                keys:
                    - composer-{{ checksum "composer.lock" }}

            - run:
                # Set TERMINUS_ENV and related environment variables.
                # https://github.com/pantheon-systems/docker-build-tools-ci/blob/1.x/scripts/set-environment
                name: dependencies
                command: ./scripts/circle-ci/variables.sh

            - run:
                command: ./scripts/circle-ci/install-globals.sh

# @todo caching

            - run:
                command: composer install  --optimize-autoloader --ignore-platform-reqs

            - save_cache:
                key: composer-{{ checksum "composer.lock" }}
                paths:
                  - vendor

            - run:
                name: everything
                command: |
                    composer install  --optimize-autoloader --ignore-platform-reqs
                    composer circle-tests
                    ./scripts/circle-ci/deploy-to-multidev-for-behavior-tests.sh







workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - behavioral
